### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by ondohotola** [lvignoli/typst-pandoc#1]
I converted an involved LaTeX document and saw the following errors
```
No render function for Block value 'Figure';
define a function `Writer.Block.Figure` that returns a string or Doc.
```
I commented the `\begin/end{figure}` out and the next error is
```
No render function for Inline value 'Cite';
define a function `Writer.Inline.Cite` that returns a string or Doc.
```
I am just a user dabbling a little in perl but have no clue how to do this. 

Any assistance would be greatly appreciated. 

`Typst` can do citations and perhaps one can make the `figure` a no-op of sorts?

**Comment by lvignoli** [comment]
Hello @ondohotola!

When I first wrote the pandoc reader 2 months ago, there were no figure function nor labelling and citations commands in Tyspt. So I left that aside, with some other features such as tables or nested lists that were too intricate.

A temporary fix is sadly to remove any call to these unsupported things from your latex document before using this pandoc filter. The full list of supported feature is available in the readme.

I'll try to update soon to at least make a no-op for blocks that are too tedious to be implemented, so that you can get a partial conversion at least.

**Comment by ondohotola** [comment]
Louis,

Thanks.

But should the \cite{LABEL} not somehow be able to be transformed into
something like @LABEL?

el

**Comment by lvignoli** [comment]
Yes, I'll fix figure and cite with the new available features.
For the rest, I'll try to provide no-ops rather than a conversion error.

**Comment by ondohotola** [comment]
Thank you so much.

**Comment by lvignoli** [comment]
@ondohotola [pandoc 3.1.2](https://github.com/jgm/pandoc/releases/tag/3.1.2) now natively support conversion **to** Typst. I expect a greater coverage of the pandoc blocks than this exteension, so your document may be convertible with the vanilla pandoc now.

Since a Typst reader is also planned, I will stop working on this Lua extension.

Closing this now :)

**Comment by ondohotola** [comment]
awesome
